//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public int id { get; set; }
        public string idArea { get; set; }
        public string idEmpleado { get; set; }
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
    }
}
